### ISSUE TITLE
Ask about the implementation

### ISSUE THREAD

**Issue by terryqj0107** [xiul-msr/e2e_dialog_challenge#1]
Excuse me . What framework is used to implement the neural network in this system? Is it the LSTM encapsulated by matlab？ Is there a duplicate version of tensorflow?

**Comment by xjli** [comment]
No using any framework for the LSTM and neural networks models in this system. All the neural models are with pure Python. But you are free to use any framework, like tensorflow, pytorch etc.

**Comment by terryqj0107** [comment]
Can this system use GPU to train the neural models？If so，how to implement？

**Comment by xjli** [comment]
Yes, you can. You can write an agent (.py) file which is derived from agent.py, this agent can be implemented with pytorch, tensorflow etc., and add this agent into the run.py file,  say agt=20, then use your own agent to run. See some agent examples from agt=1,2,3,...,13

**Comment by xjli** [comment]
@terryqj0107 , you can see one example here in DDQ, https://github.com/MiuLab/DDQ/blob/master/src/deep_dialog/agents/agent_dqn.py, this agent_dqn.py is implemented with pytorch under the framework.

**Comment by terryqj0107** [comment]
ok，thank you very much
