### ISSUE TITLE
Data for Building NLU and NLG modules?

### ISSUE THREAD

**Issue by ravi03071991** [xiul-msr/e2e_dialog_challenge#7]
Hi,

I could not find data for building models for NLU and NLG modules. Can I know where in the repository I can find them?

Regards,
D. Ravi Theja.

**Comment by xjli** [comment]
Hi, Ravi,

The intermediate data (format) for NLU and NLG are derived from the annotated data under data folder, so I did not release it. For example, NLU training data is BIO format, and NLG training data is just the raw annotated data.

So, basically, for NLU and NLG model, it depends on your design, you can use the annotated data to generate any format data to fit your NLU and NLG, and train NLU and NLG. 

Thanks,
Xiujun
