### ISSUE TITLE
About the deadline

### ISSUE THREAD

**Issue by liusih** [xiul-msr/e2e_dialog_challenge#8]
Hi , I would like to know that whether I could submit the system now? And  I did't find the submit place at this page.
![image](https://user-images.githubusercontent.com/31608942/47151623-da47b180-d30c-11e8-9015-54770e409dd9.png)

**Comment by xjli** [comment]
Hi, @liusih , I re-set the deadline to Oct. 25, now, it works, and you can submit there.

Thanks much,
Xiujun

**Comment by xjli** [comment]
Hi, liusih,

I re-set the deadline of submission system, it was open yesterday, you can
submit there.

Thanks,
Xiujun
